services:
  frontend:
    image: blog-front-dev
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    volumes: 
      - ./frontend:/usr/src/app
    ports:
      - 5173:5173
    container_name: blog-front-dev

  mongo:
    image: mongo:latest  
    container_name: mongo-container
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: your_database
    ports:
      - 27017:27017 
    volumes:
      - mongo_data:/data/db

  server:
    image: blog-back-dev
    build:
      context: ./backend
      dockerfile: dev.Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mongo

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy3
    depends_on:
      - frontend
      - server
    
volumes:
  mongo_data: