services:
  app:
    image: todo-backend
    build: .
    ports:
      - 3000:3000
    environment:
      MONGO_URL: mongodb://the_username:the_password@mongo:27017/the_database
      REDIS_URL: redis://redis:6379
